XtalOpt - GlobalSearch:GlobalSearch::LocalQueueInterface Class Reference
GlobalSearch::LocalQueueInterface Class Reference
Interface for running jobs locally.
#include <globalsearch/local.h>
Public Slots
virtual bool writeFiles (Structure *s, const QHash< QString, QString > &files) const
virtual bool startJob (Structure *s)
virtual bool stopJob (Structure *s)
virtual QueueInterface::QueueStatus getStatus (Structure *s) const
virtual bool prepareForStructureUpdate (Structure *s) const
virtual bool checkIfFileExists (Structure *s, const QString &filename, bool *exists)
virtual bool fetchFile (Structure *s, const QString &filename, QString *contents) const
virtual bool grepFile (Structure *s, const QString &matchText, const QString &filename, QStringList *matches=0, int *exitcode=0, const bool caseSensitive=true) const
virtual QDialog * dialog ()
Public Slots inherited from GlobalSearch::QueueInterface
virtual void readSettings (const QString &filename="")
virtual void writeSettings (const QString &filename="")
virtual bool writeInputFiles (Structure *s) const
virtual bool writeFiles (Structure *s, const QHash< QString, QString > &files) const =0
virtual bool startJob (Structure *s)=0
virtual bool stopJob (Structure *s)=0
virtual QueueInterface::QueueStatus getStatus (Structure *s) const =0
virtual bool prepareForStructureUpdate (Structure *s) const =0
virtual bool checkIfFileExists (Structure *s, const QString &filename, bool *exists)=0
virtual bool fetchFile (Structure *s, const QString &filename, QString *contents) const =0
virtual bool grepFile (Structure *s, const QString &matchText, const QString &filename, QStringList *matches=0, int *exitcode=0, const bool caseSensitive=true) const =0
QString getIDString () const
QStringList getTemplateFileNames () const
bool hasDialog ()
virtual QDialog * dialog ()
Public Member Functions
LocalQueueInterface (OptBase *parent, const QString &settingFile="")
virtual ~LocalQueueInterface ()
virtual bool isReadyToSearch (QString *err)
Public Member Functions inherited from GlobalSearch::QueueInterface
QueueInterface (OptBase *parent, const QString &settingFile="")
virtual ~QueueInterface ()
Protected Attributes
QHash< unsigned long,
LocalQueueProcess * > m_processes
Protected Attributes inherited from GlobalSearch::QueueInterface
OptBase * m_opt
Cached pointer to the parent OptBase class.
QString m_idString
String identifying the type of queue interface.
QStringList m_templates
bool m_hasDialog
Whether this QueueInterface has a configuration dialog.
QDialog * m_dialog
Pointer to configuration dialog (may be NULL)
Friends
class LocalQueueInterfaceConfigDialog
Additional Inherited Members
Public Types inherited from GlobalSearch::QueueInterface
enum QueueStatus {
Unknown = -1, Success, Error, Queued,
Running, CommunicationError, Started, Pending
}
Detailed Description
Interface for running jobs locally.
Author
David C. Lonie
Definition at line 59 of file local.h.
Constructor & Destructor Documentation
GlobalSearch::LocalQueueInterface::LocalQueueInterface (OptBase * parent, const QString & settingFile = "") explicit
Constructor
Parameters
parent OptBase parent
settingFile Filename from which to initialize settings.
Definition at line 38 of file local.cpp.
References GlobalSearch::QueueInterface::m_hasDialog, and GlobalSearch::QueueInterface::m_idString.
GlobalSearch::LocalQueueInterface::~LocalQueueInterface () virtual
Destructor
Definition at line 50 of file local.cpp.
References m_processes.
Member Function Documentation
bool GlobalSearch::LocalQueueInterface::checkIfFileExists (Structure * s, const QString & filename, bool * exists) virtual slot
Check if the file filename exists in the working directory of Structure s and store the result in exists.
Note
This function uses the argument exists to report whether or not the file exists. The return value indicates whether the file check was performed without errors (e.g. network errors).
Returns
True if the test encountered no errors, false otherwise.
Definition at line 305 of file local.cpp.
bool GlobalSearch::LocalQueueInterface::fetchFile (Structure * s, const QString & filename, QString * contents) const virtual slot
Retrieve the contents of the file filename for Structure s as a QString contents.
Returns
True on success, false otherwise.
Definition at line 315 of file local.cpp.
Referenced by grepFile().
QueueInterface::QueueStatus GlobalSearch::LocalQueueInterface::getStatus (Structure * s) const virtual slot
Returns
The queue status of Structure s.
Definition at line 219 of file local.cpp.
References GlobalSearch::Optimizer::checkForSuccessfulOutput(), GlobalSearch::Optimizer::checkIfOutputFileExists(), GlobalSearch::QueueInterface::Error, GlobalSearch::Structure::getIDString(), GlobalSearch::Structure::getJobID(), GlobalSearch::Structure::getStatus(), GlobalSearch::QueueInterface::m_opt, m_processes, GlobalSearch::OptBase::optimizer(), GlobalSearch::QueueInterface::Pending, GlobalSearch::QueueInterface::Running, GlobalSearch::QueueInterface::Started, GlobalSearch::Structure::Submitted, GlobalSearch::QueueInterface::Success, GlobalSearch::QueueInterface::Unknown, and GlobalSearch::OptBase::warning().
bool GlobalSearch::LocalQueueInterface::grepFile (Structure * s, const QString & matchText, const QString & filename, QStringList * matches = 0, int * exitcode = 0, const bool caseSensitive = true) const virtual slot
Grep through the file filename for Structure s's working directory, looking for matchText. The list of matches is returned in the QStringList matches and the exit status is returned as exitcode.
Possible exitcodes:
0: Matches were found, execution successful
1: No matches found, execution successful
2: Execution unsuccessful
Parameters
s Structure of interest
matchText Text to match
filename Name of file to grep
matches List of matches (return)
exitcode Exit code of grep (see details) (return)
caseSensitive If true, match case. Otherwise, perform case-insensitive search (e.g. grep -i) Default is true.
Returns
True on success, false otherwise.
Note
There are two types of failure possible here: Either the exitcode can be 2 or the function can return false. If the exitcode is 2, then grep failed to execute. If false, then there was a failure in the interface code, likely a communication error with a remote server.
On local queue interface, grep is not actually used and the exit code behavior is emulated.
Definition at line 329 of file local.cpp.
References fetchFile().
bool GlobalSearch::LocalQueueInterface::isReadyToSearch (QString * err) virtual
Check that all mandatory internal variables are set. Check this before starting a search.
Parameters
err String to be overwritten with an error message
Returns
true if all variables are initialized, false otherwise. If false, err will be overwritten with a user-friendly error message.
Reimplemented from GlobalSearch::QueueInterface.
Definition at line 66 of file local.cpp.
References GlobalSearch::OptBase::filePath, and GlobalSearch::QueueInterface::m_opt.
bool GlobalSearch::LocalQueueInterface::prepareForStructureUpdate (Structure * s) const virtual slot
Perform any work needed before calling Optimizer::update. This function mainly exists for RemoteQueue classes to copy files back from the server, but may be used for other purposes. It is guaranteed to be called by Optimizer before updating.
Parameters
s The structure that is to be updated.
Returns
True on success, false otherwise.
Definition at line 299 of file local.cpp.
bool GlobalSearch::LocalQueueInterface::startJob (Structure * s) virtual slot
Start a job for Structure s.
Note
Ensure that writeFiles is called before attempting to start the job.
Returns
True on success, false otherwise.
Definition at line 145 of file local.cpp.
References GlobalSearch::Structure::getIDString(), GlobalSearch::Structure::getJobID(), GlobalSearch::Optimizer::localRunCommand(), GlobalSearch::QueueInterface::m_opt, m_processes, GlobalSearch::OptBase::optimizer(), GlobalSearch::Structure::setJobID(), GlobalSearch::Structure::startOptTimer(), GlobalSearch::Optimizer::stderrFilename(), GlobalSearch::Optimizer::stdinFilename(), GlobalSearch::Optimizer::stdoutFilename(), and GlobalSearch::OptBase::warning().
bool GlobalSearch::LocalQueueInterface::stopJob (Structure * s) virtual slot
Stop any currently running jobs for Structure s.
Returns
True on success, false otherwise.
Definition at line 192 of file local.cpp.
References GlobalSearch::Structure::getJobID(), m_processes, GlobalSearch::Structure::setJobID(), and GlobalSearch::Structure::stopOptTimer().
bool GlobalSearch::LocalQueueInterface::writeFiles (Structure * s, const QHash< QString, QString > & files) const virtual slot
Write the input files in the hash files to the appropriate location for Structure s.
Parameters
s Structure of interest
files Key: filename, Value: text.
Note
The filenames in files must not be absolute, but relative to the structure's working directory.
Returns
True on success, false otherwise.
Definition at line 105 of file local.cpp.
Member Data Documentation
QHash<unsigned long, LocalQueueProcess*> GlobalSearch::LocalQueueInterface::m_processes protected
Look up hash for mapping jobID's to processes. Key: PID, Value: QProcess handle
Definition at line 216 of file local.h.
Referenced by getStatus(), startJob(), stopJob(), and ~LocalQueueInterface().
The documentation for this class was generated from the following files:
src/globalsearch/queueinterfaces/local.h
src/globalsearch/queueinterfaces/local.cpp