XtalOpt - API:GlobalSearch::Optimizer Class Reference
GlobalSearch::Optimizer Class Reference
The Optimizer class provides an interface between an OptBase instance and an external optimization engine.
#include <globalsearch/optimizer.h>
Public Slots
virtual bool setTemplate (const QString &filename, const QString &templateData, int optStepIndex)
virtual bool setTemplate (const QString &filename, const QStringList &templateData)
virtual bool appendTemplate (const QString &filename, const QString &templateData)
virtual bool removeAllTemplatesForOptStep (int optStepIndex)
virtual bool setData (const QString &identifier, const QVariant &data)
void setUser1 (const QString &s)
Public Member Functions
Optimizer (OptBase *parent, const QString &filename="")
virtual ~Optimizer ()
virtual void readSettings (const QString &filename="")
virtual void writeSettings (const QString &filename="")
virtual QString getIDString ()
virtual int getNumberOfOptSteps ()
virtual bool isReadyToSearch (QString *err)
virtual bool checkIfOutputFileExists (Structure *s, bool *exists)
virtual bool checkForSuccessfulOutput (Structure *s, bool *success)
virtual bool update (Structure *structure)
virtual bool load (Structure *structure)
virtual bool read (Structure *structure, const QString &filename)
virtual QString getTemplate (const QString &filename, int optStepIndex)
virtual QStringList getTemplate (const QString &filename)
virtual QVariant getData (const QString &identifier)
virtual QStringList getTemplateNames ()
virtual QStringList getDataIdentifiers ()
QString getUser1 ()
QString getUser2 ()
QString getUser3 ()
QString getUser4 ()
void setUser2 (const QString &s)
void setUser3 (const QString &s)
void setUser4 (const QString &s)
QString localRunCommand () const
QString stdinFilename () const
QString stdoutFilename () const
QString stderrFilename () const
virtual QHash< QString, QString > getInterpretedTemplates (Structure *s)
bool hasDialog ()
virtual QDialog * dialog ()
Protected Slots
virtual void updateQueueInterface ()
Protected Member Functions
virtual void readTemplatesFromSettings (const QString &filename="")
virtual void writeTemplatesToSettings (const QString &filename="")
virtual void readUserValuesFromSettings (const QString &filename="")
virtual void writeUserValuesToSettings (const QString &filename="")
virtual void readDataFromSettings (const QString &filename="")
virtual void writeDataToSettings (const QString &filename="")
QHash< QString, QStringList > & resolveTemplateHash (const QString &filename)
const QHash< QString, QStringList > & resolveTemplateHash (const QString &filename) const
virtual void fixTemplateLengths ()
Protected Attributes
QHash< QString, QVariant > m_data
QHash< QString, QStringList > m_templates
QHash< QString, QStringList > m_QITemplates
QString m_completionFilename
QStringList m_completionStrings
QStringList m_outputFilenames
QString m_localRunCommand
QString m_stdinFilename
QString m_stdoutFilename
QString m_stderrFilename
QString m_user1
QString m_user2
QString m_user3
QString m_user4
OptBase * m_opt
QString m_idString
Friends
class OptimizerConfigDialog
Detailed Description
The Optimizer class provides an interface between an OptBase instance and an external optimization engine.
Author
David C. Lonie
The Optimizer class standardizes communication between an OptBase instance and an external chemical optimization engine, such as GAMESS, ADF, VASP, etc.
The file contents may be set using the setTemplate, appendTemplate, and removeTemplate functions. These will be passed through the associated OptBase's template interpreter prior to writing.
Once the Optimizer is attached to the OptBase instance and the templates are set, the QueueManager handles all job submission, file writing, and Structure updating automatically.
Definition at line 52 of file optimizer.h.
Constructor & Destructor Documentation
GlobalSearch::Optimizer::Optimizer (OptBase * parent, const QString & filename = "") explicit
Constructor
Parameters
parent OptBase parent
filename Optional filename to load data from (scheme or resume file)
Definition at line 41 of file optimizer.cpp.
References m_idString, m_opt, m_stderrFilename, m_stdinFilename, m_stdoutFilename, GlobalSearch::OptBase::queueInterface(), readSettings(), and updateQueueInterface().
GlobalSearch::Optimizer::~Optimizer () virtual
Destructor
Definition at line 107 of file optimizer.cpp.
Member Function Documentation
bool GlobalSearch::Optimizer::appendTemplate (const QString & filename, const QString & templateData) virtual slot
Add a new optimization step for a given filename.
Parameters
filename Filename identifying the template
templateData Template string of the new optimization step.
Returns
True if successful, false otherwise.
Definition at line 583 of file optimizer.cpp.
References m_QITemplates, m_templates, and resolveTemplateHash().
bool GlobalSearch::Optimizer::checkForSuccessfulOutput (Structure * s, bool * success) virtual
Check m_completionFilename for any of the m_completionStrings in the working directory of Structure s. If any are found, success is set to true.
Note
This function uses the argument success to report whether or not m_completionFileName contains any m_completionStrings. The return value indicates whether the file check was performed without errors (e.g. network errors).
Returns
True if the test encountered no errors, false otherwise.
Definition at line 369 of file optimizer.cpp.
References GlobalSearch::QueueInterface::grepFile(), m_completionFilename, m_completionStrings, m_opt, and GlobalSearch::OptBase::queueInterface().
Referenced by GlobalSearch::LocalQueueInterface::getStatus().
bool GlobalSearch::Optimizer::checkIfOutputFileExists (Structure * s, bool * exists) virtual
Check if the file m_completionFilename exists in the working directory of Structure s and store the result in exists.
Note
This function uses the argument exists to report whether or not the file exists. The return value indicates whether the file check was performed without errors (e.g. network errors).
Returns
True if the test encountered no errors, false otherwise.
Definition at line 362 of file optimizer.cpp.
References GlobalSearch::QueueInterface::checkIfFileExists(), m_completionFilename, m_opt, and GlobalSearch::OptBase::queueInterface().
Referenced by GlobalSearch::LocalQueueInterface::getStatus().
void GlobalSearch::Optimizer::fixTemplateLengths () protected virtual
Ensure that all template lists in m_templates and m_QITemplates contain getNumberOfOptSteps() optimization steps.
If a template list has too few entries, empty strings are appended.
Definition at line 672 of file optimizer.cpp.
References getNumberOfOptSteps(), m_QITemplates, and m_templates.
Referenced by readTemplatesFromSettings().
QVariant GlobalSearch::Optimizer::getData (const QString & identifier) virtual
Get generic data associated with the optimizer.
Parameters
identifier QString identifying the data needed.
Returns
A QVariant version of the generic data.
Definition at line 625 of file optimizer.cpp.
References m_data.
virtual QStringList GlobalSearch::Optimizer::getDataIdentifiers () inline virtual
Returns
All strings that identify valid generic data sets.
Definition at line 217 of file optimizer.h.
References m_data.
Referenced by readDataFromSettings(), and writeDataToSettings().
virtual QString GlobalSearch::Optimizer::getIDString () inline virtual
Returns
A string identifying the Optimizer
Definition at line 96 of file optimizer.h.
References m_idString.
Referenced by readDataFromSettings(), readTemplatesFromSettings(), readUserValuesFromSettings(), GlobalSearch::AbstractEditTab::saveScheme(), writeDataToSettings(), writeTemplatesToSettings(), and writeUserValuesToSettings().
QHash< QString, QString > GlobalSearch::Optimizer::getInterpretedTemplates (Structure * s) virtual
Interpret all templates in m_templates at the Structure's current optimization step.
Parameters
s Structure of interest
Returns
A hash containing the interpreted templates, key: filename, value: file contents
Definition at line 281 of file optimizer.cpp.
References GlobalSearch::Structure::getCurrentOptStep(), GlobalSearch::Structure::getIDString(), getNumberOfOptSteps(), GlobalSearch::OptBase::interpretTemplate(), m_opt, m_QITemplates, m_templates, GlobalSearch::OptBase::optimizer(), GlobalSearch::OptBase::queueInterface(), and GlobalSearch::QueueInterface::stopJob().
Referenced by GlobalSearch::QueueInterface::writeInputFiles().
int GlobalSearch::Optimizer::getNumberOfOptSteps () virtual
Returns
The total number of optimization steps
Definition at line 535 of file optimizer.cpp.
References m_templates.
Referenced by GlobalSearch::AbstractEditTab::appendOptStep(), fixTemplateLengths(), getInterpretedTemplates(), getTemplate(), GlobalSearch::AbstractEditTab::populateOptStepList(), removeAllTemplatesForOptStep(), GlobalSearch::AbstractEditTab::removeCurrentOptStep(), GlobalSearch::AbstractEditTab::saveCurrentTemplate(), setTemplate(), GlobalSearch::AbstractEditTab::updateEditWidget(), and updateQueueInterface().
QString GlobalSearch::Optimizer::getTemplate (const QString & filename, int optStepIndex) virtual
Return a specified template.
Parameters
filename Filename of template
optStepIndex Optimization step index of template to retrieve.
Returns
The requested template
Definition at line 565 of file optimizer.cpp.
References getNumberOfOptSteps(), m_QITemplates, m_templates, and resolveTemplateHash().
Referenced by GlobalSearch::AbstractEditTab::updateEditWidget().
QStringList GlobalSearch::Optimizer::getTemplate (const QString & filename) virtual
Return a list of all templates for a given filename
Parameters
filename Filename of template
Returns
A list of all template matching the given filename, in order of optimization step.
Definition at line 575 of file optimizer.cpp.
References m_QITemplates, m_templates, and resolveTemplateHash().
virtual QStringList GlobalSearch::Optimizer::getTemplateNames () inline virtual
Returns
All filenames that the optimizer can store templates for.
Definition at line 212 of file optimizer.h.
References m_templates.
Referenced by GlobalSearch::AbstractEditTab::getTemplateNames(), readTemplatesFromSettings(), and writeTemplatesToSettings().
QString GlobalSearch::Optimizer::getUser1 () inline
Returns
A user customizable string that is used in template interpretation.
Definition at line 223 of file optimizer.h.
References m_user1.
Referenced by GlobalSearch::OptBase::interpretKeyword_base(), and GlobalSearch::AbstractEditTab::updateGUI().
QString GlobalSearch::Optimizer::getUser2 () inline
Returns
A user customizable string that is used in template interpretation.
Definition at line 229 of file optimizer.h.
References m_user2.
Referenced by GlobalSearch::OptBase::interpretKeyword_base(), and GlobalSearch::AbstractEditTab::updateGUI().
QString GlobalSearch::Optimizer::getUser3 () inline
Returns
A user customizable string that is used in template interpretation.
Definition at line 235 of file optimizer.h.
References m_user3.
Referenced by GlobalSearch::OptBase::interpretKeyword_base(), and GlobalSearch::AbstractEditTab::updateGUI().
QString GlobalSearch::Optimizer::getUser4 () inline
Returns
A user customizable string that is used in template interpretation.
Definition at line 241 of file optimizer.h.
References m_user4.
Referenced by GlobalSearch::OptBase::interpretKeyword_base(), and GlobalSearch::AbstractEditTab::updateGUI().
virtual bool GlobalSearch::Optimizer::isReadyToSearch (QString * err) inline virtual
Check that all mandatory internal variables are set. Check this before starting a search.
Parameters
err String to be overwritten with an error message
Returns
true if all variables are initialized, false otherwise. If false, err will be overwritten with a user-friendly error message.
Definition at line 113 of file optimizer.h.
bool GlobalSearch::Optimizer::load (Structure * structure) virtual
Update the Structure from the files in the Structure's local file path.
Parameters
structure Structure to be updated.
Returns
True if successful, false otherwise.
See also
update
read
Definition at line 430 of file optimizer.cpp.
References m_opt, m_outputFilenames, read(), and GlobalSearch::OptBase::warning().
QString GlobalSearch::Optimizer::localRunCommand () const inline
Command line used in local execution
Details given in m_localRunCommand.
See also
stdinFilename
stdoutFilename
stderrFilename
m_localRunCommand
m_stdinFilename
m_stdoutFilename
m_stderrFilename
Definition at line 344 of file optimizer.h.
References m_localRunCommand.
Referenced by GlobalSearch::LocalQueueInterface::startJob().
bool GlobalSearch::Optimizer::read (Structure * structure, const QString & filename) virtual
Update the Structure from the specified filename.
Parameters
structure Structure to be updated
filename Filename to read
Returns
True if successful, false otherwise.
See also
update
load
Definition at line 451 of file optimizer.cpp.
References GlobalSearch::OptBase::error(), GlobalSearch::Structure::getIDString(), GlobalSearch::OptBase::isStarting, m_opt, GlobalSearch::OptBase::sOBMutex, GlobalSearch::Structure::updateAndAddToHistory(), GlobalSearch::Structure::updateAndSkipHistory(), and GlobalSearch::OptBase::warning().
Referenced by load(), and update().
void GlobalSearch::Optimizer::readDataFromSettings (const QString & filename = "") protected virtual
Parameters
filename Scheme or state file from which to load all generic data values in m_data
Definition at line 175 of file optimizer.cpp.
References getDataIdentifiers(), GlobalSearch::OptBase::getIDString(), getIDString(), m_data, and m_opt.
Referenced by readSettings().
void GlobalSearch::Optimizer::readSettings (const QString & filename = "") virtual
Read optimizer data from file (.scheme or .state). If called without an argument, this function does nothing, i.e. it will not read optimizer data from the system config file.
Parameters
filename Scheme or state file to load data from.
See also
writeSettings
Definition at line 111 of file optimizer.cpp.
References readDataFromSettings(), readTemplatesFromSettings(), and readUserValuesFromSettings().
Referenced by Optimizer().
void GlobalSearch::Optimizer::readTemplatesFromSettings (const QString & filename = "") protected virtual
Parameters
filename Scheme or state file from which to load all templates in m_templates
Definition at line 125 of file optimizer.cpp.
References fixTemplateLengths(), GlobalSearch::OptBase::getIDString(), getIDString(), GlobalSearch::QueueInterface::getIDString(), getTemplateNames(), m_opt, m_QITemplates, m_templates, and GlobalSearch::OptBase::queueInterface().
Referenced by readSettings().
void GlobalSearch::Optimizer::readUserValuesFromSettings (const QString & filename = "") protected virtual
Parameters
filename Scheme or state file from which to load all user values (m_user[1-4])
Definition at line 161 of file optimizer.cpp.
References GlobalSearch::OptBase::getIDString(), getIDString(), m_opt, m_user1, m_user2, m_user3, and m_user4.
Referenced by readSettings().
bool GlobalSearch::Optimizer::removeAllTemplatesForOptStep (int optStepIndex) virtual slot
Removes all template entries for the given optstep.
Note
This function will remove the template for the current Optimizer and QueueInterface, but will not modify any "data" entries in the Optimizer.
Parameters
optStepIndex Optimization step index to remove
Returns
True if successful, false otherwise.
Definition at line 593 of file optimizer.cpp.
References getNumberOfOptSteps(), m_QITemplates, and m_templates.
Referenced by GlobalSearch::AbstractEditTab::removeCurrentOptStep().
QHash< QString, QStringList > & GlobalSearch::Optimizer::resolveTemplateHash (const QString & filename) protected
Determine which internal template hash contains filename and return a reference to the correct hash.
Definition at line 633 of file optimizer.cpp.
References m_QITemplates, and m_templates.
Referenced by appendTemplate(), getTemplate(), and setTemplate().
const QHash< QString, QStringList > & GlobalSearch::Optimizer::resolveTemplateHash (const QString & filename) const protected
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Determine which internal template hash contains filename and return a reference to the correct hash.
Definition at line 653 of file optimizer.cpp.
References m_QITemplates, and m_templates.
bool GlobalSearch::Optimizer::setData (const QString & identifier, const QVariant & data) virtual slot
Set a generic data entry.
Parameters
identifier A valid data identifier
data QVariant of data
Returns
True if successful, false otherwise.
See also
getData
getDataIdentifiers
Definition at line 617 of file optimizer.cpp.
References m_data.
bool GlobalSearch::Optimizer::setTemplate (const QString & filename, const QString & templateData, int optStepIndex) virtual slot
Set the template for the specified filename and optimization step.
Parameters
filename Filename of template
templateData Template string
optStepIndex Optimization step (index, starts at 0)
Returns
True if successful, false otherwise.
Definition at line 542 of file optimizer.cpp.
References getNumberOfOptSteps(), m_QITemplates, m_templates, and resolveTemplateHash().
Referenced by GlobalSearch::AbstractEditTab::saveCurrentTemplate().
bool GlobalSearch::Optimizer::setTemplate (const QString & filename, const QStringList & templateData) virtual slot
Set all templates for the specified filename.
Parameters
filename Filename of template
templateData List of template strings in order of optimization step
Returns
True if successful, false otherwise.
Definition at line 554 of file optimizer.cpp.
References m_QITemplates, m_templates, and resolveTemplateHash().
void GlobalSearch::Optimizer::setUser1 (const QString & s) inline slot
Parameters
s A user customizable string that is used in template interpretation.
Definition at line 311 of file optimizer.h.
References m_user1.
Referenced by GlobalSearch::AbstractEditTab::updateUserValues().
void GlobalSearch::Optimizer::setUser2 (const QString & s) inline
Parameters
s A user customizable string that is used in template interpretation.
Definition at line 317 of file optimizer.h.
References m_user2.
Referenced by GlobalSearch::AbstractEditTab::updateUserValues().
void GlobalSearch::Optimizer::setUser3 (const QString & s) inline
Parameters
s A user customizable string that is used in template interpretation.
Definition at line 323 of file optimizer.h.
References m_user3.
Referenced by GlobalSearch::AbstractEditTab::updateUserValues().
void GlobalSearch::Optimizer::setUser4 (const QString & s) inline
Parameters
s A user customizable string that is used in template interpretation.
Definition at line 329 of file optimizer.h.
References m_user4.
Referenced by GlobalSearch::AbstractEditTab::updateUserValues().
QString GlobalSearch::Optimizer::stderrFilename () const inline
Filename for standard error
Details given in m_localRunCommand.
See also
localRunCommand
stdinFilename
stdoutFilename
m_localRunCommand
m_stdinFilename
m_stdoutFilename
m_stderrFilename
Definition at line 389 of file optimizer.h.
References m_stderrFilename.
Referenced by GlobalSearch::LocalQueueInterface::startJob().
QString GlobalSearch::Optimizer::stdinFilename () const inline
Filename for standard input
Details given in m_localRunCommand.
See also
localRunCommand
stdoutFilename
stderrFilename
m_localRunCommand
m_stdinFilename
m_stdoutFilename
m_stderrFilename
Definition at line 359 of file optimizer.h.
References m_stdinFilename.
Referenced by GlobalSearch::LocalQueueInterface::startJob().
QString GlobalSearch::Optimizer::stdoutFilename () const inline
Filename for standard output
Details given in m_localRunCommand.
See also
localRunCommand
stdinFilename
stderrFilename
m_localRunCommand
m_stdinFilename
m_stdoutFilename
m_stderrFilename
Definition at line 374 of file optimizer.h.
References m_stdoutFilename.
Referenced by GlobalSearch::LocalQueueInterface::startJob().
bool GlobalSearch::Optimizer::update (Structure * structure) virtual
Copy the files from the Structure's remote path to the local path, and then update the Structure based on the optimization results.
Parameters
structure Structure to be updated.
Returns
True if successful, false otherwise.
See also
load
read
Definition at line 393 of file optimizer.cpp.
References GlobalSearch::Structure::getIDString(), m_opt, m_outputFilenames, GlobalSearch::QueueInterface::prepareForStructureUpdate(), GlobalSearch::OptBase::queueInterface(), read(), GlobalSearch::Structure::setJobID(), GlobalSearch::Structure::stopOptTimer(), and GlobalSearch::OptBase::warning().
void GlobalSearch::Optimizer::updateQueueInterface () protected virtual slot
Update the m_QITemplates hash.
Automatically connected to m_opt's queueInterfaceChanged signal. Should not need to be called directly.
Definition at line 343 of file optimizer.cpp.
References getNumberOfOptSteps(), GlobalSearch::QueueInterface::getTemplateFileNames(), m_opt, m_QITemplates, and GlobalSearch::OptBase::queueInterface().
Referenced by Optimizer().
void GlobalSearch::Optimizer::writeDataToSettings (const QString & filename = "") protected virtual
Parameters
filename Scheme or state file in which to write all generic data values in m_data
Definition at line 266 of file optimizer.cpp.
References getDataIdentifiers(), GlobalSearch::OptBase::getIDString(), getIDString(), m_data, and m_opt.
Referenced by writeSettings().
void GlobalSearch::Optimizer::writeSettings (const QString & filename = "") virtual
Write optimizer data to file (.scheme or .state). If called without an argument, this function does nothing, i.e. it will not write optimizer data to the system config file.
Parameters
filename Scheme or state file to write data to.
See also
readSettings
Definition at line 190 of file optimizer.cpp.
References m_opt, GlobalSearch::OptBase::queueInterface(), writeDataToSettings(), GlobalSearch::QueueInterface::writeSettings(), writeTemplatesToSettings(), and writeUserValuesToSettings().
void GlobalSearch::Optimizer::writeTemplatesToSettings (const QString & filename = "") protected virtual
Parameters
filename Scheme or state file in which to write all templates in m_templates
Definition at line 209 of file optimizer.cpp.
References GlobalSearch::OptBase::getIDString(), getIDString(), GlobalSearch::QueueInterface::getIDString(), getTemplateNames(), m_opt, m_QITemplates, m_templates, and GlobalSearch::OptBase::queueInterface().
Referenced by writeSettings().
void GlobalSearch::Optimizer::writeUserValuesToSettings (const QString & filename = "") protected virtual
Parameters
filename Scheme or state file in which to write all user values (m_user[1-4])
Definition at line 240 of file optimizer.cpp.
References GlobalSearch::OptBase::getIDString(), getIDString(), m_opt, m_user1, m_user2, m_user3, and m_user4.
Referenced by writeSettings().
Member Data Documentation
QString GlobalSearch::Optimizer::m_completionFilename protected
File to check if optimization has complete successfully.
See also
m_completionString
Definition at line 512 of file optimizer.h.
Referenced by checkForSuccessfulOutput(), and checkIfOutputFileExists().
QStringList GlobalSearch::Optimizer::m_completionStrings protected
String to search for in m_completionFilename when checking if optimization has complete successfully.
See also
m_completionFilename.
Definition at line 519 of file optimizer.h.
Referenced by checkForSuccessfulOutput().
QHash<QString, QVariant> GlobalSearch::Optimizer::m_data protected
Store generic data types. This is not commonly used, see XtalOpt's VASPOptimizer for an example where it is used to store information about pseudopotentials.
Definition at line 470 of file optimizer.h.
Referenced by getData(), getDataIdentifiers(), readDataFromSettings(), setData(), and writeDataToSettings().
QString GlobalSearch::Optimizer::m_idString protected
Unique identification string for this Optimizer.
Definition at line 640 of file optimizer.h.
Referenced by getIDString(), and Optimizer().
QString GlobalSearch::Optimizer::m_localRunCommand protected
Commandline instruction to run this program locally
Three common scenarios:
VASP-esque: $ vasp Runs in working directory reading from predefined input filenames (ie. POSCAR). Set m_localRunCommand="vasp", and m_stdinFilename=m_stdoutFilename=m_stderrFilename="";
GULP-esque: $ gulp < job.gin 1>job.got 2>job.err
Runs in working directory using redirection to specify input/output. Set m_localRunCommand="gulp", m_stdinFilename="job.gin", m_stdoutFilename="job.got", m_stderrFilename="job.err".
MOPAC-esque: $ mopac job
Runs in working directory, specifying either an input filename or a base name. In both cases, put the entire command line into m_localRunCommand, ="mopac job", m_stdinFilename=m_stdoutFilename=m_stderrFilename=""
Stdin/out/err is not used (="") by default.
See also
localRunCommand
stdinFilename
stdoutFilename
stderrFilename
m_stdinFilename
m_stdoutFilename
m_stderrFilename
Definition at line 561 of file optimizer.h.
Referenced by localRunCommand().
OptBase* GlobalSearch::Optimizer::m_opt protected
Cached pointer to the associated OptBase instance
Definition at line 635 of file optimizer.h.
Referenced by checkForSuccessfulOutput(), checkIfOutputFileExists(), dialog(), getInterpretedTemplates(), load(), Optimizer(), read(), readDataFromSettings(), readTemplatesFromSettings(), readUserValuesFromSettings(), update(), updateQueueInterface(), writeDataToSettings(), writeSettings(), writeTemplatesToSettings(), and writeUserValuesToSettings().
QStringList GlobalSearch::Optimizer::m_outputFilenames protected
List of filenames to check when updating structure (will be checked in order of index).
Definition at line 525 of file optimizer.h.
Referenced by load(), and update().
QHash<QString, QStringList > GlobalSearch::Optimizer::m_QITemplates protected
Stores all template data for the current QueueInterface. Key is the filename to be written and the value is a list of corresponding templates in order of optimization step.
Definition at line 506 of file optimizer.h.
Referenced by appendTemplate(), fixTemplateLengths(), getInterpretedTemplates(), getTemplate(), readTemplatesFromSettings(), removeAllTemplatesForOptStep(), resolveTemplateHash(), setTemplate(), updateQueueInterface(), and writeTemplatesToSettings().
QString GlobalSearch::Optimizer::m_stderrFilename protected
Filename for standard error
Details given in m_localRunCommand.
See also
localRunCommand
stdinFilename
stdoutFilename
stderrFilename
m_localRunCommand
m_stdinFilename
m_stdoutFilename
Definition at line 606 of file optimizer.h.
Referenced by Optimizer(), and stderrFilename().
QString GlobalSearch::Optimizer::m_stdinFilename protected
Filename for standard input
Details given in m_localRunCommand.
See also
localRunCommand
stdinFilename
stdoutFilename
stderrFilename
m_localRunCommand
m_stdoutFilename
m_stderrFilename
Definition at line 576 of file optimizer.h.
Referenced by Optimizer(), and stdinFilename().
QString GlobalSearch::Optimizer::m_stdoutFilename protected
Filename for standard output
Details given in m_localRunCommand.
See also
localRunCommand
stdinFilename
stdoutFilename
stderrFilename
m_localRunCommand
m_stdinFilename
m_stderrFilename
Definition at line 591 of file optimizer.h.
Referenced by Optimizer(), and stdoutFilename().
QHash<QString, QStringList > GlobalSearch::Optimizer::m_templates protected
Stores all template data for this optimizer. Key is the filename to be written and the value is a list of corresponding templates in order of optimization step.
Definition at line 499 of file optimizer.h.
Referenced by appendTemplate(), fixTemplateLengths(), getInterpretedTemplates(), getNumberOfOptSteps(), getTemplate(), getTemplateNames(), readTemplatesFromSettings(), removeAllTemplatesForOptStep(), resolveTemplateHash(), setTemplate(), and writeTemplatesToSettings().
QString GlobalSearch::Optimizer::m_user1 protected
User defined string that is used during template interpretation.
Definition at line 612 of file optimizer.h.
Referenced by getUser1(), readUserValuesFromSettings(), setUser1(), and writeUserValuesToSettings().
QString GlobalSearch::Optimizer::m_user2 protected
User defined string that is used during template interpretation.
Definition at line 618 of file optimizer.h.
Referenced by getUser2(), readUserValuesFromSettings(), setUser2(), and writeUserValuesToSettings().
QString GlobalSearch::Optimizer::m_user3 protected
User defined string that is used during template interpretation.
Definition at line 624 of file optimizer.h.
Referenced by getUser3(), readUserValuesFromSettings(), setUser3(), and writeUserValuesToSettings().
QString GlobalSearch::Optimizer::m_user4 protected
User defined string that is used during template interpretation.
Definition at line 630 of file optimizer.h.
Referenced by getUser4(), readUserValuesFromSettings(), setUser4(), and writeUserValuesToSettings().
The documentation for this class was generated from the following files:
src/globalsearch/optimizer.h
src/globalsearch/optimizer.cpp