XtalOpt - API:Dialog access
Dialog access
Functions
bool GlobalSearch::Optimizer::hasDialog ()
virtual QDialog * GlobalSearch::Optimizer::dialog ()
bool GlobalSearch::QueueInterface::hasDialog ()
virtual QDialog * GlobalSearch::QueueInterface::dialog ()
Public Slots
virtual QDialog * GlobalSearch::LocalQueueInterface::dialog ()
Detailed Description
Function Documentation
virtual QDialog* GlobalSearch::QueueInterface::dialog () inline virtual
Returns
The configuration dialog for this QueueInterface, if it exists, otherwise 0.
See also
hasDialog()
Definition at line 272 of file queueinterface.h.
Referenced by GlobalSearch::AbstractEditTab::configureQueueInterface().
QDialog * GlobalSearch::Optimizer::dialog () virtual
Returns
The configuration dialog for this QueueInterface, if it exists, otherwise 0.
See also
hasDialog()
Definition at line 329 of file optimizer.cpp.
References GlobalSearch::OptBase::dialog(), and GlobalSearch::Optimizer::m_opt.
Referenced by GlobalSearch::AbstractEditTab::configureOptimizer().
bool GlobalSearch::QueueInterface::hasDialog () inline
Returns
True if this QueueInterface has a configuration dialog.
See also
dialog()
Definition at line 264 of file queueinterface.h.
References GlobalSearch::QueueInterface::m_hasDialog.
Referenced by GlobalSearch::AbstractEditTab::configureQueueInterface(), GlobalSearch::AbstractEditTab::updateGUI(), and GlobalSearch::AbstractEditTab::updateQueueInterface().
bool GlobalSearch::Optimizer::hasDialog () inline
Returns
True if this QueueInterface has a configuration dialog.
See also
dialog()
Definition at line 409 of file optimizer.h.
Referenced by GlobalSearch::AbstractEditTab::configureOptimizer(), and GlobalSearch::AbstractEditTab::updateOptimizer().
Public Slots
QDialog * GlobalSearch::LocalQueueInterface::dialog () virtual slot
Returns
The configuration dialog for this QueueInterface, if it exists, otherwise 0.
See also
hasDialog()
Definition at line 376 of file local.cpp.
References GlobalSearch::OptBase::dialog(), GlobalSearch::QueueInterface::m_dialog, and GlobalSearch::QueueInterface::m_opt.