GlobalSearch: GlobalSearch::AbstractEditTab Class Reference
GlobalSearch::AbstractEditTab Class Reference
Abstract class implementing a template editor.
#include <globalsearch/abstractedittab.h>
Public Slots
virtual void lockGUI ()
virtual void updateGUI ()
virtual void updateEditWidget ()
virtual void showHelp ()
virtual void saveCurrentTemplate ()
virtual void populateOptStepList ()
virtual void populateTemplates ()
virtual void appendOptStep ()
virtual void removeCurrentOptStep ()
virtual void saveScheme ()
virtual void loadScheme ()
virtual QStringList getTemplateNames ()
Public Slots inherited from GlobalSearch::AbstractTab
virtual void lockGUI ()
Signals
void optimizerChanged (Optimizer *)
void queueInterfaceChanged (QueueInterface *)
Signals inherited from GlobalSearch::AbstractTab
void moleculeChanged (GlobalSearch::Structure *)
void startingBackgroundProcessing ()
void finishedBackgroundProcessing ()
void initialized ()
Public Member Functions
AbstractEditTab (AbstractDialog *parent, OptBase *p)
virtual ~AbstractEditTab ()
Public Member Functions inherited from GlobalSearch::AbstractTab
AbstractTab (AbstractDialog *parent, OptBase *p)
virtual ~AbstractTab ()
QWidget * getTabWidget ()
virtual void readSettings (const QString &filename="")
virtual void writeSettings (const QString &filename="")
virtual void updateGUI ()
virtual void disconnectGUI ()
Protected Slots
virtual void initialize ()
virtual void updateUserValues ()
virtual void updateQueueInterface ()
virtual void updateOptimizer ()
virtual void configureQueueInterface ()
virtual void configureOptimizer ()
Protected Slots inherited from GlobalSearch::AbstractTab
virtual void initialize ()
void setBusyCursor ()
void clearBusyCursor ()
Protected Attributes
QList< Optimizer * > m_optimizers
QList< QueueInterface * > m_queueInterfaces
QComboBox * ui_combo_queueInterfaces
Cached GUI pointer. This is set in DefaultEditTab.
QComboBox * ui_combo_optimizers
Cached GUI pointer. This is set in DefaultEditTab.
QComboBox * ui_combo_templates
Cached GUI pointer. This is set in DefaultEditTab.
QLineEdit * ui_edit_user1
Cached GUI pointer. This is set in DefaultEditTab.
QLineEdit * ui_edit_user2
Cached GUI pointer. This is set in DefaultEditTab.
QLineEdit * ui_edit_user3
Cached GUI pointer. This is set in DefaultEditTab.
QLineEdit * ui_edit_user4
Cached GUI pointer. This is set in DefaultEditTab.
QListWidget * ui_list_edit
Cached GUI pointer. This is set in DefaultEditTab.
QListWidget * ui_list_optStep
Cached GUI pointer. This is set in DefaultEditTab.
QPushButton * ui_push_add
Cached GUI pointer. This is set in DefaultEditTab.
QPushButton * ui_push_help
Cached GUI pointer. This is set in DefaultEditTab.
QPushButton * ui_push_loadScheme
Cached GUI pointer. This is set in DefaultEditTab.
QPushButton * ui_push_optimizerConfig
Cached GUI pointer. This is set in DefaultEditTab.
QPushButton * ui_push_queueInterfaceConfig
Cached GUI pointer. This is set in DefaultEditTab.
QPushButton * ui_push_remove
Cached GUI pointer. This is set in DefaultEditTab.
QPushButton * ui_push_saveScheme
Cached GUI pointer. This is set in DefaultEditTab.
QTextEdit * ui_edit_edit
Cached GUI pointer. This is set in DefaultEditTab.
Protected Attributes inherited from GlobalSearch::AbstractTab
QWidget * m_tab_widget
The actual widget that will be made into a tab.
AbstractDialog * m_dialog
A pointer to the parent dialog.
OptBase * m_opt
A pointer to the associated OptBase class.
bool m_isInitialized
Set to true once initialized() completes.
Detailed Description
Abstract class implementing a template editor.
Author
David C. Lonie
Definition at line 45 of file abstractedittab.h.
Constructor & Destructor Documentation
GlobalSearch::AbstractEditTab::AbstractEditTab (AbstractDialog * parent, OptBase * p) explicit
Constructor
Parameters
parent AbstractDialog that will use this tab
p Associated OptBase
Definition at line 35 of file abstractedittab.cpp.
GlobalSearch::AbstractEditTab::~AbstractEditTab () virtual
Destructor
Definition at line 148 of file abstractedittab.cpp.
Member Function Documentation
void GlobalSearch::AbstractEditTab::appendOptStep () virtual slot
Create a new optstep at the end of the optstep list. It will initialize using the currently selected optstep's templates.
Definition at line 411 of file abstractedittab.cpp.
References GlobalSearch::Optimizer::getNumberOfOptSteps(), getTemplateNames(), GlobalSearch::AbstractTab::m_opt, GlobalSearch::OptBase::optimizer(), populateOptStepList(), and ui_list_optStep.
Referenced by initialize().
void GlobalSearch::AbstractEditTab::configureOptimizer () protected virtual slot
Launch the Optimizer configuration dialog.
Definition at line 276 of file abstractedittab.cpp.
References GlobalSearch::Optimizer::dialog(), GlobalSearch::Optimizer::hasDialog(), GlobalSearch::AbstractTab::m_opt, and GlobalSearch::OptBase::optimizer().
Referenced by initialize().
void GlobalSearch::AbstractEditTab::configureQueueInterface () protected virtual slot
Launch the QueueInterface configuration dialog.
Definition at line 264 of file abstractedittab.cpp.
References GlobalSearch::QueueInterface::dialog(), GlobalSearch::QueueInterface::hasDialog(), GlobalSearch::AbstractTab::m_opt, and GlobalSearch::OptBase::queueInterface().
Referenced by initialize().
QStringList GlobalSearch::AbstractEditTab::getTemplateNames () virtual slot
Returns
A list of the available template names for the current QueueInterface and Optimizer.
Definition at line 288 of file abstractedittab.cpp.
References GlobalSearch::QueueInterface::getTemplateFileNames(), GlobalSearch::Optimizer::getTemplateNames(), GlobalSearch::AbstractTab::m_isInitialized, GlobalSearch::AbstractTab::m_opt, GlobalSearch::OptBase::optimizer(), and GlobalSearch::OptBase::queueInterface().
Referenced by appendOptStep(), populateTemplates(), saveCurrentTemplate(), and updateEditWidget().
void GlobalSearch::AbstractEditTab::initialize () protected virtual slot
Create connections and initialize GUI.
Definition at line 54 of file abstractedittab.cpp.
References appendOptStep(), configureOptimizer(), configureQueueInterface(), GlobalSearch::AbstractTab::initialize(), loadScheme(), GlobalSearch::AbstractTab::m_dialog, GlobalSearch::AbstractTab::m_opt, m_optimizers, m_queueInterfaces, optimizerChanged(), populateOptStepList(), populateTemplates(), queueInterfaceChanged(), removeCurrentOptStep(), saveCurrentTemplate(), saveScheme(), showHelp(), ui_combo_optimizers, ui_combo_queueInterfaces, ui_combo_templates, ui_edit_edit, ui_edit_user1, ui_edit_user2, ui_edit_user3, ui_edit_user4, ui_list_optStep, ui_push_add, ui_push_help, ui_push_loadScheme, ui_push_optimizerConfig, ui_push_queueInterfaceConfig, ui_push_remove, ui_push_saveScheme, updateEditWidget(), updateGUI(), updateOptimizer(), updateQueueInterface(), and updateUserValues().
Referenced by GlobalSearch::DefaultEditTab::initialize().
void GlobalSearch::AbstractEditTab::loadScheme () virtual slot
Load an optimization scheme from a file. This will prompt the user for the filename.
Definition at line 468 of file abstractedittab.cpp.
References GlobalSearch::OptBase::getIDString(), GlobalSearch::AbstractTab::m_opt, and GlobalSearch::AbstractTab::readSettings().
Referenced by initialize().
void GlobalSearch::AbstractEditTab::lockGUI () virtual slot
Lock GUI elements that shouldn't change once the search begins.
Definition at line 195 of file abstractedittab.cpp.
References ui_combo_optimizers, and ui_combo_queueInterfaces.
void GlobalSearch::AbstractEditTab::optimizerChanged (Optimizer *) signal
Emitted when the Optimizer changes.
Referenced by initialize(), and updateOptimizer().
void GlobalSearch::AbstractEditTab::populateOptStepList () virtual slot
Generate the list of optsteps.
Definition at line 384 of file abstractedittab.cpp.
References GlobalSearch::Optimizer::getNumberOfOptSteps(), GlobalSearch::AbstractTab::m_isInitialized, GlobalSearch::AbstractTab::m_opt, GlobalSearch::OptBase::optimizer(), GlobalSearch::OptBase::queueInterface(), and ui_list_optStep.
Referenced by appendOptStep(), initialize(), removeCurrentOptStep(), saveCurrentTemplate(), updateEditWidget(), and updateGUI().
void GlobalSearch::AbstractEditTab::populateTemplates () virtual slot
Fill the template selection combo using the template names for the current QueueInterface and Optimizer.
Definition at line 299 of file abstractedittab.cpp.
References getTemplateNames(), GlobalSearch::AbstractTab::m_isInitialized, and ui_combo_templates.
Referenced by initialize(), and updateGUI().
void GlobalSearch::AbstractEditTab::queueInterfaceChanged (QueueInterface *) signal
Emitted when the QueueInterface changes.
Referenced by initialize(), and updateQueueInterface().
void GlobalSearch::AbstractEditTab::removeCurrentOptStep () virtual slot
Delete the currently selected optstep.
Definition at line 435 of file abstractedittab.cpp.
References GlobalSearch::Optimizer::getNumberOfOptSteps(), GlobalSearch::AbstractTab::m_opt, GlobalSearch::OptBase::optimizer(), populateOptStepList(), GlobalSearch::Optimizer::removeAllTemplatesForOptStep(), and ui_list_optStep.
Referenced by initialize().
void GlobalSearch::AbstractEditTab::saveCurrentTemplate () virtual slot
Save the text in the template editor to the appropriate template list.
Definition at line 349 of file abstractedittab.cpp.
References GlobalSearch::Optimizer::getNumberOfOptSteps(), getTemplateNames(), GlobalSearch::AbstractTab::m_opt, GlobalSearch::OptBase::optimizer(), populateOptStepList(), GlobalSearch::Optimizer::setTemplate(), ui_combo_templates, ui_edit_edit, and ui_list_optStep.
Referenced by initialize().
void GlobalSearch::AbstractEditTab::saveScheme () virtual slot
Save the current optimization scheme. This will prompt for the user to specify the filename.
Definition at line 447 of file abstractedittab.cpp.
References GlobalSearch::OptBase::getIDString(), GlobalSearch::Optimizer::getIDString(), GlobalSearch::AbstractTab::m_opt, GlobalSearch::OptBase::optimizer(), and GlobalSearch::AbstractTab::writeSettings().
Referenced by initialize().
void GlobalSearch::AbstractEditTab::showHelp () virtual slot
Popup a message box displaying the keyword documentation.
Definition at line 201 of file abstractedittab.cpp.
References GlobalSearch::OptBase::getTemplateKeywordHelp(), GlobalSearch::AbstractTab::m_dialog, and GlobalSearch::AbstractTab::m_opt.
Referenced by initialize().
void GlobalSearch::AbstractEditTab::updateEditWidget () virtual slot
Display the currently selected template in the text editor.
Definition at line 311 of file abstractedittab.cpp.
References GlobalSearch::Optimizer::getNumberOfOptSteps(), GlobalSearch::Optimizer::getTemplate(), getTemplateNames(), GlobalSearch::AbstractTab::m_isInitialized, GlobalSearch::AbstractTab::m_opt, GlobalSearch::OptBase::optimizer(), populateOptStepList(), ui_combo_templates, ui_edit_edit, ui_list_edit, and ui_list_optStep.
Referenced by initialize(), and updateGUI().
void GlobalSearch::AbstractEditTab::updateGUI () virtual slot
Force a refresh of the GUI elements using the internal state.
Definition at line 152 of file abstractedittab.cpp.
References GlobalSearch::Optimizer::getUser1(), GlobalSearch::Optimizer::getUser2(), GlobalSearch::Optimizer::getUser3(), GlobalSearch::Optimizer::getUser4(), GlobalSearch::QueueInterface::hasDialog(), GlobalSearch::AbstractTab::m_isInitialized, GlobalSearch::AbstractTab::m_opt, m_optimizers, m_queueInterfaces, GlobalSearch::OptBase::optimizer(), populateOptStepList(), populateTemplates(), GlobalSearch::OptBase::queueInterface(), ui_combo_optimizers, ui_combo_queueInterfaces, ui_edit_user1, ui_edit_user2, ui_edit_user3, ui_edit_user4, ui_push_queueInterfaceConfig, and updateEditWidget().
Referenced by initialize().
void GlobalSearch::AbstractEditTab::updateOptimizer () protected virtual slot
Determine the currently selected Optimizer and emit optimizerChanged if it differs from the current one.
Definition at line 236 of file abstractedittab.cpp.
References GlobalSearch::Optimizer::hasDialog(), GlobalSearch::AbstractTab::m_opt, m_optimizers, GlobalSearch::OptBase::optimizer(), optimizerChanged(), ui_combo_optimizers, and ui_push_optimizerConfig.
Referenced by initialize().
void GlobalSearch::AbstractEditTab::updateQueueInterface () protected virtual slot
Determine the currently selected QueueInterface and emit queueInterfaceChanged if it differs from the current one.
Definition at line 208 of file abstractedittab.cpp.
References GlobalSearch::QueueInterface::hasDialog(), GlobalSearch::AbstractTab::m_opt, m_queueInterfaces, GlobalSearch::OptBase::queueInterface(), queueInterfaceChanged(), ui_combo_queueInterfaces, and ui_push_queueInterfaceConfig.
Referenced by initialize().
void GlobalSearch::AbstractEditTab::updateUserValues () protected virtual slot
Refresh the "userX" line edits.
Definition at line 376 of file abstractedittab.cpp.
References GlobalSearch::AbstractTab::m_opt, GlobalSearch::OptBase::optimizer(), GlobalSearch::Optimizer::setUser1(), GlobalSearch::Optimizer::setUser2(), GlobalSearch::Optimizer::setUser3(), GlobalSearch::Optimizer::setUser4(), ui_edit_user1, ui_edit_user2, ui_edit_user3, and ui_edit_user4.
Referenced by initialize().
Member Data Documentation
QList<Optimizer*> GlobalSearch::AbstractEditTab::m_optimizers protected
List of all optimizers. This must be filled in derived classes prior to calling initialize()
Definition at line 177 of file abstractedittab.h.
Referenced by initialize(), updateGUI(), and updateOptimizer().
QList<QueueInterface*> GlobalSearch::AbstractEditTab::m_queueInterfaces protected
List of all QueueInterfaces. This must be filled in derived classes prior to calling initialize()
Definition at line 181 of file abstractedittab.h.
Referenced by initialize(), updateGUI(), and updateQueueInterface().
The documentation for this class was generated from the following files:
src/globalsearch/ui/abstractedittab.h
src/globalsearch/ui/abstractedittab.cpp